services:
  api:
    build: .
    container_name: openfinance-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/openfinance
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: openfinance-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
